In [246]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from catboost import CatBoostClassifier
import joblib

In [183]:
df=pd.read_csv("bank-full.csv",delimiter=";")
df_main=df.copy()
df_label=df['y']
df.drop(['y'],axis=1,inplace=True)

#### no need to run this code the file is also present in the folder

In [184]:
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)
# profile.to_file("report.html")

In [185]:
xtrain,xtest,ytrain,ytest=train_test_split(df,df_label,test_size=0.2,random_state=21)

In [186]:
num_df = xtrain.select_dtypes(include='number').copy()
num_coloumns=num_df.columns
num_df

       age  balance  day  duration  campaign  pdays  previous
1533    50        0    8       393         2     -1         0
39881   50     3370    2       160         2     -1         0
7432    36        0   29       211         6     -1         0
30441   55     1765    5       445         1    267         1
39017   28      352   18       431         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
16432   57      215   23       288         9     -1         0
8964    56       62    5       243         1     -1         0
5944    30      306   26       372        14     -1         0
5327    28      370   23       108         5     -1         0
15305   52     2102   18       292         2     -1         0

[36168 rows x 7 columns]

In [187]:
ordinal_cols = ['education', 'month']
nominal_cols = ['job','marital','default','housing','loan','contact','poutcome']

In [188]:
ordinal_df=xtrain[ordinal_cols].copy()
nominal_df=xtrain[nominal_cols].copy()

In [189]:
nominal_df

               job  marital default housing loan   contact poutcome
1533    technician   single      no     yes   no   unknown  unknown
39881   technician  married      no      no   no  cellular  unknown
7432    management   single      no     yes   no   unknown  unknown
30441  blue-collar  married      no     yes   no  cellular  failure
39017       admin.   single      no     yes  yes  cellular  unknown
...            ...      ...     ...     ...  ...       ...      ...
16432   management  married      no      no  yes  cellular  unknown
8964    technician  married      no      no  yes   unknown  unknown
5944    unemployed   single      no      no   no   unknown  unknown
5327    technician   single      no     yes   no   unknown  unknown
15305   technician  married      no     yes   no  cellular  unknown

[36168 rows x 7 columns]

In [190]:
num_pipeline =Pipeline([
    ("stdscaller",StandardScaler()),
    ])

In [191]:
ordinal_pipeline=Pipeline([
    ("ordinalencoder",OrdinalEncoder(categories=[
        ['unknown', 'primary', 'secondary', 'tertiary'],
        ['jan','feb','mar','apr','may','jun',
         'jul','aug','sep','oct','nov','dec']
    ]))
    ])

In [192]:
nominal_pipeline=Pipeline([
    ("onehotencoder",OneHotEncoder())
    ])

In [193]:
transformer=ColumnTransformer([
    ("num",num_pipeline,num_df.columns),
    ("ordinal",ordinal_pipeline,ordinal_df.columns),
    ("nominal",nominal_pipeline,nominal_df.columns),
],remainder='drop')

In [194]:
base_model=LogisticRegression()
lb=LabelEncoder()
train_data_y=lb.fit_transform(ytrain)
train_data=transformer.fit_transform(xtrain)

In [195]:
base_model.fit(train_data,train_data_y,)

LogisticRegression()

In [196]:
prediction_base=base_model.predict(transformer.fit_transform(xtest))

In [197]:
print(classification_report(lb.fit_transform(ytest),prediction_base))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94      7983
           1       0.64      0.33      0.44      1060

    accuracy                           0.90      9043
   macro avg       0.78      0.65      0.69      9043
weighted avg       0.88      0.90      0.89      9043

In [203]:
category_feature = xtrain.select_dtypes(include=['object', 'category']).columns.tolist()

In [209]:
catboost = CatBoostClassifier(
    iterations=2000,
    depth=8,
    learning_rate=0.03,
    eval_metric='F1',
    auto_class_weights='Balanced'
)

In [210]:
catboost.fit(xtrain,ytrain,cat_features=category_feature)

0:	learn: 0.8133972	total: 74.5ms	remaining: 2m 28s
1:	learn: 0.8185015	total: 128ms	remaining: 2m 8s
2:	learn: 0.8252923	total: 194ms	remaining: 2m 9s
3:	learn: 0.8281179	total: 264ms	remaining: 2m 11s
4:	learn: 0.8322007	total: 342ms	remaining: 2m 16s
5:	learn: 0.8373545	total: 417ms	remaining: 2m 18s
6:	learn: 0.8395850	total: 488ms	remaining: 2m 18s
7:	learn: 0.8390607	total: 557ms	remaining: 2m 18s
8:	learn: 0.8366028	total: 630ms	remaining: 2m 19s
9:	learn: 0.8361258	total: 684ms	remaining: 2m 16s
10:	learn: 0.8365704	total: 743ms	remaining: 2m 14s
11:	learn: 0.8379817	total: 829ms	remaining: 2m 17s
12:	learn: 0.8341270	total: 889ms	remaining: 2m 15s
13:	learn: 0.8384227	total: 979ms	remaining: 2m 18s
14:	learn: 0.8380444	total: 1.06s	remaining: 2m 20s
15:	learn: 0.8382053	total: 1.14s	remaining: 2m 21s
16:	learn: 0.8402022	total: 1.23s	remaining: 2m 22s
17:	learn: 0.8418092	total: 1.31s	remaining: 2m 24s
18:	learn: 0.8415131	total: 1.39s	remaining: 2m 25s
19:	learn: 0.8423396	total: 1.48s	remaining: 2m 26s
20:	learn: 0.8425830	total: 1.55s	remaining: 2m 25s
21:	learn: 0.8415106	total: 1.63s	remaining: 2m 26s
22:	learn: 0.8434801	total: 1.7s	remaining: 2m 26s
23:	learn: 0.8431736	total: 1.77s	remaining: 2m 25s
24:	learn: 0.8435135	total: 1.83s	remaining: 2m 24s
25:	learn: 0.8443036	total: 1.91s	remaining: 2m 24s
26:	learn: 0.8451244	total: 1.98s	remaining: 2m 24s
27:	learn: 0.8449863	total: 2.07s	remaining: 2m 25s
28:	learn: 0.8462854	total: 2.15s	remaining: 2m 26s
29:	learn: 0.8471847	total: 2.24s	remaining: 2m 26s
30:	learn: 0.8472460	total: 2.32s	remaining: 2m 27s
31:	learn: 0.8480359	total: 2.41s	remaining: 2m 28s
32:	learn: 0.8485008	total: 2.49s	remaining: 2m 28s
33:	learn: 0.8496570	total: 2.58s	remaining: 2m 28s
34:	learn: 0.8500763	total: 2.66s	remaining: 2m 29s
35:	learn: 0.8512515	total: 2.74s	remaining: 2m 29s
36:	learn: 0.8518086	total: 2.81s	remaining: 2m 29s
37:	learn: 0.8519283	total: 2.88s	remaining: 2m 28s
38:	learn: 0.8519413	total: 2.94s	remaining: 2m 28s
39:	learn: 0.8525806	total: 3.02s	remaining: 2m 28s
40:	learn: 0.8537457	total: 3.09s	remaining: 2m 27s
41:	learn: 0.8535591	total: 3.16s	remaining: 2m 27s
42:	learn: 0.8541055	total: 3.24s	remaining: 2m 27s
43:	learn: 0.8544207	total: 3.32s	remaining: 2m 27s
44:	learn: 0.8551196	total: 3.4s	remaining: 2m 27s
45:	learn: 0.8547590	total: 3.49s	remaining: 2m 28s
46:	learn: 0.8548228	total: 3.57s	remaining: 2m 28s
47:	learn: 0.8552722	total: 3.65s	remaining: 2m 28s
48:	learn: 0.8546186	total: 3.74s	remaining: 2m 28s
49:	learn: 0.8556480	total: 3.83s	remaining: 2m 29s
50:	learn: 0.8565076	total: 3.92s	remaining: 2m 29s
51:	learn: 0.8572069	total: 3.99s	remaining: 2m 29s
52:	learn: 0.8567033	total: 4.07s	remaining: 2m 29s
53:	learn: 0.8572585	total: 4.14s	remaining: 2m 29s
54:	learn: 0.8578139	total: 4.21s	remaining: 2m 29s
55:	learn: 0.8581048	total: 4.29s	remaining: 2m 29s
56:	learn: 0.8583548	total: 4.38s	remaining: 2m 29s
57:	learn: 0.8589474	total: 4.46s	remaining: 2m 29s
58:	learn: 0.8588020	total: 4.54s	remaining: 2m 29s
59:	learn: 0.8585256	total: 4.62s	remaining: 2m 29s
60:	learn: 0.8583925	total: 4.7s	remaining: 2m 29s
61:	learn: 0.8590127	total: 4.79s	remaining: 2m 29s
62:	learn: 0.8590780	total: 4.87s	remaining: 2m 29s
63:	learn: 0.8594206	total: 4.96s	remaining: 2m 29s
64:	learn: 0.8597763	total: 5.04s	remaining: 2m 30s
65:	learn: 0.8609217	total: 5.12s	remaining: 2m 29s
66:	learn: 0.8607768	total: 5.19s	remaining: 2m 29s
67:	learn: 0.8609610	total: 5.28s	remaining: 2m 30s
68:	learn: 0.8609876	total: 5.36s	remaining: 2m 29s
69:	learn: 0.8611455	total: 5.43s	remaining: 2m 29s
70:	learn: 0.8610271	total: 5.5s	remaining: 2m 29s
71:	learn: 0.8614747	total: 5.58s	remaining: 2m 29s
72:	learn: 0.8619216	total: 5.66s	remaining: 2m 29s
73:	learn: 0.8618037	total: 5.73s	remaining: 2m 29s
74:	learn: 0.8616461	total: 5.8s	remaining: 2m 28s
75:	learn: 0.8620806	total: 5.87s	remaining: 2m 28s
76:	learn: 0.8620406	total: 5.96s	remaining: 2m 28s
77:	learn: 0.8621329	total: 6.05s	remaining: 2m 29s
78:	learn: 0.8629224	total: 6.13s	remaining: 2m 29s
79:	learn: 0.8625673	total: 6.21s	remaining: 2m 29s
80:	learn: 0.8630544	total: 6.29s	remaining: 2m 29s
81:	learn: 0.8636721	total: 6.38s	remaining: 2m 29s
82:	learn: 0.8635672	total: 6.46s	remaining: 2m 29s
83:	learn: 0.8639883	total: 6.55s	remaining: 2m 29s
84:	learn: 0.8641581	total: 6.63s	remaining: 2m 29s
85:	learn: 0.8646429	total: 6.71s	remaining: 2m 29s
86:	learn: 0.8651812	total: 6.79s	remaining: 2m 29s
87:	learn: 0.8651692	total: 6.87s	remaining: 2m 29s
88:	learn: 0.8652882	total: 6.94s	remaining: 2m 29s
89:	learn: 0.8657340	total: 7.01s	remaining: 2m 28s
90:	learn: 0.8660089	total: 7.08s	remaining: 2m 28s
91:	learn: 0.8658913	total: 7.16s	remaining: 2m 28s
92:	learn: 0.8654986	total: 7.23s	remaining: 2m 28s
93:	learn: 0.8658927	total: 7.32s	remaining: 2m 28s
94:	learn: 0.8659707	total: 7.4s	remaining: 2m 28s
95:	learn: 0.8661280	total: 7.48s	remaining: 2m 28s
96:	learn: 0.8665485	total: 7.56s	remaining: 2m 28s
97:	learn: 0.8673742	total: 7.64s	remaining: 2m 28s
98:	learn: 0.8672170	total: 7.73s	remaining: 2m 28s
99:	learn: 0.8672435	total: 7.77s	remaining: 2m 27s
100:	learn: 0.8675067	total: 7.85s	remaining: 2m 27s
101:	learn: 0.8679893	total: 7.93s	remaining: 2m 27s
102:	learn: 0.8679117	total: 8.01s	remaining: 2m 27s
103:	learn: 0.8680310	total: 8.06s	remaining: 2m 26s
104:	learn: 0.8681860	total: 8.14s	remaining: 2m 26s
105:	learn: 0.8683960	total: 8.22s	remaining: 2m 26s
106:	learn: 0.8684867	total: 8.29s	remaining: 2m 26s
107:	learn: 0.8685663	total: 8.37s	remaining: 2m 26s
108:	learn: 0.8688138	total: 8.45s	remaining: 2m 26s
109:	learn: 0.8691939	total: 8.53s	remaining: 2m 26s
110:	learn: 0.8697813	total: 8.62s	remaining: 2m 26s
111:	learn: 0.8695606	total: 8.72s	remaining: 2m 26s
112:	learn: 0.8697439	total: 8.8s	remaining: 2m 26s
113:	learn: 0.8698609	total: 8.83s	remaining: 2m 26s
114:	learn: 0.8700283	total: 8.91s	remaining: 2m 26s
115:	learn: 0.8699885	total: 9s	remaining: 2m 26s
116:	learn: 0.8701187	total: 9.09s	remaining: 2m 26s
117:	learn: 0.8700789	total: 9.18s	remaining: 2m 26s
118:	learn: 0.8707821	total: 9.26s	remaining: 2m 26s
119:	learn: 0.8707556	total: 9.29s	remaining: 2m 25s
120:	learn: 0.8704558	total: 9.36s	remaining: 2m 25s
121:	learn: 0.8703390	total: 9.4s	remaining: 2m 24s
122:	learn: 0.8705858	total: 9.48s	remaining: 2m 24s
123:	learn: 0.8705991	total: 9.5s	remaining: 2m 23s
124:	learn: 0.8707954	total: 9.58s	remaining: 2m 23s
125:	learn: 0.8709784	total: 9.64s	remaining: 2m 23s
126:	learn: 0.8711614	total: 9.72s	remaining: 2m 23s
127:	learn: 0.8710713	total: 9.79s	remaining: 2m 23s
128:	learn: 0.8712411	total: 9.87s	remaining: 2m 23s
129:	learn: 0.8711614	total: 9.95s	remaining: 2m 23s
130:	learn: 0.8716071	total: 10s	remaining: 2m 23s
131:	learn: 0.8719597	total: 10.1s	remaining: 2m 23s
132:	learn: 0.8718432	total: 10.2s	remaining: 2m 23s
133:	learn: 0.8725483	total: 10.3s	remaining: 2m 23s
134:	learn: 0.8728742	total: 10.4s	remaining: 2m 23s
135:	learn: 0.8729772	total: 10.5s	remaining: 2m 23s
136:	learn: 0.8730171	total: 10.5s	remaining: 2m 23s
137:	learn: 0.8729905	total: 10.6s	remaining: 2m 23s
138:	learn: 0.8733694	total: 10.7s	remaining: 2m 23s
139:	learn: 0.8732797	total: 10.8s	remaining: 2m 22s
140:	learn: 0.8737482	total: 10.8s	remaining: 2m 22s
141:	learn: 0.8736684	total: 10.9s	remaining: 2m 22s
142:	learn: 0.8743821	total: 11s	remaining: 2m 22s
143:	learn: 0.8739672	total: 11.1s	remaining: 2m 22s
144:	learn: 0.8740967	total: 11.1s	remaining: 2m 22s
145:	learn: 0.8741499	total: 11.2s	remaining: 2m 22s
146:	learn: 0.8747339	total: 11.3s	remaining: 2m 22s
147:	learn: 0.8747244	total: 11.4s	remaining: 2m 22s
148:	learn: 0.8753841	total: 11.5s	remaining: 2m 22s
149:	learn: 0.8754373	total: 11.6s	remaining: 2m 22s
150:	learn: 0.8755665	total: 11.7s	remaining: 2m 22s
151:	learn: 0.8756957	total: 11.7s	remaining: 2m 22s
152:	learn: 0.8759447	total: 11.8s	remaining: 2m 22s
153:	learn: 0.8765542	total: 11.9s	remaining: 2m 22s
154:	learn: 0.8766208	total: 12s	remaining: 2m 22s
155:	learn: 0.8763136	total: 12s	remaining: 2m 22s
156:	learn: 0.8766251	total: 12.1s	remaining: 2m 22s
157:	learn: 0.8772076	total: 12.2s	remaining: 2m 22s
158:	learn: 0.8772832	total: 12.3s	remaining: 2m 21s
159:	learn: 0.8777764	total: 12.3s	remaining: 2m 21s
160:	learn: 0.8774921	total: 12.4s	remaining: 2m 21s
161:	learn: 0.8778165	total: 12.5s	remaining: 2m 21s
162:	learn: 0.8775588	total: 12.6s	remaining: 2m 21s
163:	learn: 0.8778298	total: 12.7s	remaining: 2m 21s
164:	learn: 0.8778965	total: 12.8s	remaining: 2m 22s
165:	learn: 0.8778298	total: 12.9s	remaining: 2m 22s
166:	learn: 0.8779986	total: 12.9s	remaining: 2m 21s
167:	learn: 0.8783848	total: 13s	remaining: 2m 21s
168:	learn: 0.8785668	total: 13s	remaining: 2m 21s
169:	learn: 0.8783095	total: 13.1s	remaining: 2m 21s
170:	learn: 0.8782341	total: 13.2s	remaining: 2m 21s
171:	learn: 0.8784162	total: 13.3s	remaining: 2m 20s
172:	learn: 0.8788557	total: 13.3s	remaining: 2m 20s
173:	learn: 0.8785716	total: 13.4s	remaining: 2m 20s
174:	learn: 0.8786117	total: 13.5s	remaining: 2m 20s
175:	learn: 0.8789358	total: 13.6s	remaining: 2m 20s
176:	learn: 0.8788739	total: 13.6s	remaining: 2m 20s
177:	learn: 0.8789140	total: 13.7s	remaining: 2m 20s
178:	learn: 0.8791762	total: 13.8s	remaining: 2m 20s
179:	learn: 0.8796422	total: 13.9s	remaining: 2m 20s
180:	learn: 0.8798725	total: 14s	remaining: 2m 20s
181:	learn: 0.8802230	total: 14.1s	remaining: 2m 20s
182:	learn: 0.8802631	total: 14.1s	remaining: 2m 20s
183:	learn: 0.8798777	total: 14.2s	remaining: 2m 20s
184:	learn: 0.8799579	total: 14.3s	remaining: 2m 20s
185:	learn: 0.8800864	total: 14.3s	remaining: 2m 19s
186:	learn: 0.8804102	total: 14.4s	remaining: 2m 19s
187:	learn: 0.8805520	total: 14.5s	remaining: 2m 19s
188:	learn: 0.8805253	total: 14.6s	remaining: 2m 19s
189:	learn: 0.8805253	total: 14.6s	remaining: 2m 19s
190:	learn: 0.8810442	total: 14.7s	remaining: 2m 19s
191:	learn: 0.8813008	total: 14.8s	remaining: 2m 18s
192:	learn: 0.8812394	total: 14.8s	remaining: 2m 18s
193:	learn: 0.8813409	total: 14.9s	remaining: 2m 18s
194:	learn: 0.8813409	total: 15s	remaining: 2m 18s
195:	learn: 0.8813331	total: 15s	remaining: 2m 18s
196:	learn: 0.8819455	total: 15.1s	remaining: 2m 18s
197:	learn: 0.8818440	total: 15.2s	remaining: 2m 18s
198:	learn: 0.8820258	total: 15.3s	remaining: 2m 18s
199:	learn: 0.8818095	total: 15.4s	remaining: 2m 18s
200:	learn: 0.8818229	total: 15.4s	remaining: 2m 17s
201:	learn: 0.8819780	total: 15.5s	remaining: 2m 17s
202:	learn: 0.8821062	total: 15.5s	remaining: 2m 17s
203:	learn: 0.8824372	total: 15.6s	remaining: 2m 17s
204:	learn: 0.8822612	total: 15.7s	remaining: 2m 17s
205:	learn: 0.8822880	total: 15.7s	remaining: 2m 17s
206:	learn: 0.8827395	total: 15.8s	remaining: 2m 16s
207:	learn: 0.8828542	total: 15.9s	remaining: 2m 16s
208:	learn: 0.8829957	total: 15.9s	remaining: 2m 16s
209:	learn: 0.8831908	total: 16s	remaining: 2m 16s
210:	learn: 0.8833858	total: 16.1s	remaining: 2m 16s
211:	learn: 0.8833858	total: 16.2s	remaining: 2m 16s
212:	learn: 0.8832980	total: 16.2s	remaining: 2m 16s
213:	learn: 0.8832236	total: 16.3s	remaining: 2m 16s
214:	learn: 0.8832773	total: 16.4s	remaining: 2m 16s
215:	learn: 0.8838904	total: 16.5s	remaining: 2m 16s
216:	learn: 0.8839307	total: 16.6s	remaining: 2m 16s
217:	learn: 0.8840514	total: 16.7s	remaining: 2m 16s
218:	learn: 0.8839101	total: 16.7s	remaining: 2m 16s
219:	learn: 0.8838966	total: 16.8s	remaining: 2m 16s
220:	learn: 0.8840783	total: 16.9s	remaining: 2m 16s
221:	learn: 0.8840783	total: 17s	remaining: 2m 16s
222:	learn: 0.8840783	total: 17.1s	remaining: 2m 16s
223:	learn: 0.8840514	total: 17.1s	remaining: 2m 15s
224:	learn: 0.8842196	total: 17.2s	remaining: 2m 15s
225:	learn: 0.8845693	total: 17.3s	remaining: 2m 15s
226:	learn: 0.8846703	total: 17.4s	remaining: 2m 15s
227:	learn: 0.8847777	total: 17.5s	remaining: 2m 15s
228:	learn: 0.8847642	total: 17.5s	remaining: 2m 15s
229:	learn: 0.8848179	total: 17.6s	remaining: 2m 15s
230:	learn: 0.8850129	total: 17.7s	remaining: 2m 15s
231:	learn: 0.8850869	total: 17.8s	remaining: 2m 15s
232:	learn: 0.8849726	total: 17.9s	remaining: 2m 15s
233:	learn: 0.8852684	total: 18s	remaining: 2m 15s
234:	learn: 0.8852550	total: 18.1s	remaining: 2m 15s
235:	learn: 0.8853759	total: 18.1s	remaining: 2m 15s
236:	learn: 0.8856581	total: 18.2s	remaining: 2m 15s
237:	learn: 0.8855304	total: 18.3s	remaining: 2m 15s
238:	learn: 0.8855036	total: 18.4s	remaining: 2m 15s
239:	learn: 0.8855842	total: 18.5s	remaining: 2m 15s
240:	learn: 0.8858799	total: 18.6s	remaining: 2m 15s
241:	learn: 0.8863768	total: 18.6s	remaining: 2m 15s
242:	learn: 0.8863902	total: 18.7s	remaining: 2m 15s
243:	learn: 0.8862023	total: 18.8s	remaining: 2m 14s
244:	learn: 0.8861351	total: 18.8s	remaining: 2m 14s
245:	learn: 0.8863702	total: 18.9s	remaining: 2m 14s
246:	learn: 0.8866387	total: 19s	remaining: 2m 14s
247:	learn: 0.8866522	total: 19.1s	remaining: 2m 14s
248:	learn: 0.8866522	total: 19.1s	remaining: 2m 14s
249:	learn: 0.8865984	total: 19.2s	remaining: 2m 14s
250:	learn: 0.8866791	total: 19.3s	remaining: 2m 14s
251:	learn: 0.8866522	total: 19.4s	remaining: 2m 14s
252:	learn: 0.8866522	total: 19.4s	remaining: 2m 14s
253:	learn: 0.8867662	total: 19.5s	remaining: 2m 14s
254:	learn: 0.8869340	total: 19.6s	remaining: 2m 14s
255:	learn: 0.8869340	total: 19.7s	remaining: 2m 14s
256:	learn: 0.8869679	total: 19.7s	remaining: 2m 13s
257:	learn: 0.8870147	total: 19.8s	remaining: 2m 13s
258:	learn: 0.8873503	total: 19.9s	remaining: 2m 13s
259:	learn: 0.8872632	total: 20s	remaining: 2m 13s
260:	learn: 0.8872901	total: 20.1s	remaining: 2m 13s
261:	learn: 0.8871627	total: 20.1s	remaining: 2m 13s
262:	learn: 0.8874579	total: 20.2s	remaining: 2m 13s
263:	learn: 0.8874920	total: 20.3s	remaining: 2m 13s
264:	learn: 0.8875324	total: 20.4s	remaining: 2m 13s
265:	learn: 0.8875189	total: 20.4s	remaining: 2m 13s
266:	learn: 0.8870961	total: 20.5s	remaining: 2m 13s
267:	learn: 0.8870826	total: 20.6s	remaining: 2m 13s
268:	learn: 0.8871159	total: 20.7s	remaining: 2m 13s
269:	learn: 0.8872236	total: 20.8s	remaining: 2m 13s
270:	learn: 0.8872371	total: 20.9s	remaining: 2m 13s
271:	learn: 0.8873914	total: 20.9s	remaining: 2m 12s
272:	learn: 0.8873914	total: 21s	remaining: 2m 12s
273:	learn: 0.8876670	total: 21s	remaining: 2m 12s
274:	learn: 0.8875665	total: 21.1s	remaining: 2m 12s
275:	learn: 0.8875934	total: 21.2s	remaining: 2m 12s
276:	learn: 0.8875799	total: 21.3s	remaining: 2m 12s
277:	learn: 0.8877343	total: 21.3s	remaining: 2m 12s
278:	learn: 0.8881434	total: 21.4s	remaining: 2m 12s
279:	learn: 0.8882708	total: 21.5s	remaining: 2m 12s
280:	learn: 0.8884385	total: 21.6s	remaining: 2m 11s
281:	learn: 0.8885254	total: 21.7s	remaining: 2m 11s
282:	learn: 0.8887200	total: 21.7s	remaining: 2m 11s
283:	learn: 0.8890898	total: 21.8s	remaining: 2m 11s
284:	learn: 0.8889626	total: 21.9s	remaining: 2m 11s
285:	learn: 0.8888952	total: 22s	remaining: 2m 11s
286:	learn: 0.8890898	total: 22.1s	remaining: 2m 11s
287:	learn: 0.8893442	total: 22.2s	remaining: 2m 11s
288:	learn: 0.8895387	total: 22.3s	remaining: 2m 11s
289:	learn: 0.8895522	total: 22.3s	remaining: 2m 11s
290:	learn: 0.8899008	total: 22.4s	remaining: 2m 11s
291:	learn: 0.8898738	total: 22.5s	remaining: 2m 11s
292:	learn: 0.8896601	total: 22.6s	remaining: 2m 11s
293:	learn: 0.8897737	total: 22.6s	remaining: 2m 11s
294:	learn: 0.8897602	total: 22.7s	remaining: 2m 11s
295:	learn: 0.8899953	total: 22.7s	remaining: 2m 10s
296:	learn: 0.8902168	total: 22.8s	remaining: 2m 10s
297:	learn: 0.8905248	total: 22.9s	remaining: 2m 10s
298:	learn: 0.8902707	total: 22.9s	remaining: 2m 10s
299:	learn: 0.8905248	total: 23s	remaining: 2m 10s
300:	learn: 0.8904843	total: 23.1s	remaining: 2m 10s
301:	learn: 0.8904438	total: 23.2s	remaining: 2m 10s
302:	learn: 0.8905843	total: 23.3s	remaining: 2m 10s
303:	learn: 0.8904978	total: 23.4s	remaining: 2m 10s
304:	learn: 0.8905193	total: 23.4s	remaining: 2m 10s
305:	learn: 0.8909542	total: 23.5s	remaining: 2m 10s
306:	learn: 0.8908408	total: 23.6s	remaining: 2m 9s
307:	learn: 0.8908273	total: 23.6s	remaining: 2m 9s
308:	learn: 0.8908543	total: 23.7s	remaining: 2m 9s
309:	learn: 0.8909893	total: 23.7s	remaining: 2m 9s
310:	learn: 0.8908353	total: 23.8s	remaining: 2m 9s
311:	learn: 0.8907353	total: 23.9s	remaining: 2m 9s
312:	learn: 0.8907488	total: 23.9s	remaining: 2m 8s
313:	learn: 0.8907623	total: 23.9s	remaining: 2m 8s
314:	learn: 0.8913513	total: 24s	remaining: 2m 8s
315:	learn: 0.8914053	total: 24.1s	remaining: 2m 8s
316:	learn: 0.8915323	total: 24.2s	remaining: 2m 8s
317:	learn: 0.8915593	total: 24.2s	remaining: 2m 8s
318:	learn: 0.8915728	total: 24.3s	remaining: 2m 8s
319:	learn: 0.8913001	total: 24.4s	remaining: 2m 8s
320:	learn: 0.8916486	total: 24.5s	remaining: 2m 8s
321:	learn: 0.8919024	total: 24.6s	remaining: 2m 8s
322:	learn: 0.8919430	total: 24.6s	remaining: 2m 7s
323:	learn: 0.8916757	total: 24.7s	remaining: 2m 7s
324:	learn: 0.8919160	total: 24.8s	remaining: 2m 7s
325:	learn: 0.8919430	total: 24.9s	remaining: 2m 7s
326:	learn: 0.8923911	total: 25s	remaining: 2m 7s
327:	learn: 0.8922508	total: 25s	remaining: 2m 7s
328:	learn: 0.8924317	total: 25.1s	remaining: 2m 7s
329:	learn: 0.8926076	total: 25.2s	remaining: 2m 7s
330:	learn: 0.8925534	total: 25.3s	remaining: 2m 7s
331:	learn: 0.8925534	total: 25.3s	remaining: 2m 7s
332:	learn: 0.8923269	total: 25.4s	remaining: 2m 7s
333:	learn: 0.8927294	total: 25.5s	remaining: 2m 7s
334:	learn: 0.8926161	total: 25.5s	remaining: 2m 6s
335:	learn: 0.8929829	total: 25.6s	remaining: 2m 6s
336:	learn: 0.8931367	total: 25.7s	remaining: 2m 6s
337:	learn: 0.8931367	total: 25.8s	remaining: 2m 6s
338:	learn: 0.8932093	total: 25.9s	remaining: 2m 6s
339:	learn: 0.8931367	total: 26s	remaining: 2m 6s
340:	learn: 0.8931502	total: 26.1s	remaining: 2m 6s
341:	learn: 0.8931367	total: 26.1s	remaining: 2m 6s
342:	learn: 0.8935438	total: 26.2s	remaining: 2m 6s
343:	learn: 0.8934578	total: 26.2s	remaining: 2m 6s
344:	learn: 0.8934984	total: 26.3s	remaining: 2m 6s
345:	learn: 0.8936250	total: 26.4s	remaining: 2m 6s
346:	learn: 0.8936115	total: 26.5s	remaining: 2m 6s
347:	learn: 0.8936115	total: 26.5s	remaining: 2m 5s
348:	learn: 0.8934578	total: 26.6s	remaining: 2m 5s
349:	learn: 0.8936386	total: 26.7s	remaining: 2m 5s
350:	learn: 0.8936250	total: 26.7s	remaining: 2m 5s
351:	learn: 0.8938782	total: 26.8s	remaining: 2m 5s
352:	learn: 0.8939053	total: 26.9s	remaining: 2m 5s
353:	learn: 0.8939053	total: 27s	remaining: 2m 5s
354:	learn: 0.8939595	total: 27.1s	remaining: 2m 5s
355:	learn: 0.8944203	total: 27.1s	remaining: 2m 5s
356:	learn: 0.8946733	total: 27.2s	remaining: 2m 5s
357:	learn: 0.8947817	total: 27.3s	remaining: 2m 5s
358:	learn: 0.8949623	total: 27.4s	remaining: 2m 5s
359:	learn: 0.8949352	total: 27.5s	remaining: 2m 5s
360:	learn: 0.8948223	total: 27.5s	remaining: 2m 5s
361:	learn: 0.8948223	total: 27.6s	remaining: 2m 4s
362:	learn: 0.8949037	total: 27.7s	remaining: 2m 4s
363:	learn: 0.8948630	total: 27.8s	remaining: 2m 4s
364:	learn: 0.8948630	total: 27.8s	remaining: 2m 4s
365:	learn: 0.8949037	total: 27.9s	remaining: 2m 4s
366:	learn: 0.8950572	total: 28s	remaining: 2m 4s
367:	learn: 0.8952693	total: 28.1s	remaining: 2m 4s
368:	learn: 0.8954634	total: 28.2s	remaining: 2m 4s
369:	learn: 0.8956575	total: 28.2s	remaining: 2m 4s
370:	learn: 0.8957118	total: 28.3s	remaining: 2m 4s
371:	learn: 0.8958923	total: 28.4s	remaining: 2m 4s
372:	learn: 0.8957211	total: 28.5s	remaining: 2m 4s
373:	learn: 0.8957211	total: 28.6s	remaining: 2m 4s
374:	learn: 0.8955948	total: 28.7s	remaining: 2m 4s
375:	learn: 0.8957075	total: 28.7s	remaining: 2m 4s
376:	learn: 0.8955948	total: 28.8s	remaining: 2m 4s
377:	learn: 0.8957482	total: 28.9s	remaining: 2m 3s
378:	learn: 0.8960510	total: 29s	remaining: 2m 3s
379:	learn: 0.8962628	total: 29s	remaining: 2m 3s
380:	learn: 0.8960781	total: 29.1s	remaining: 2m 3s
381:	learn: 0.8961596	total: 29.2s	remaining: 2m 3s

CatBoostClassifier(auto_class_weights='Balanced', depth=8, eval_metric='F1', iterations=2000, learning_rate=0.03)

In [211]:
prediction_catboost=catboost.predict(xtest)

In [212]:
print(classification_report(ytest,prediction_catboost))

              precision    recall  f1-score   support

          no       0.97      0.89      0.93      7983
         yes       0.50      0.81      0.62      1060

    accuracy                           0.88      9043
   macro avg       0.73      0.85      0.77      9043
weighted avg       0.92      0.88      0.89      9043

In [218]:
ytrain

1533      no
39881    yes
7432      no
30441     no
39017    yes
        ...
16432     no
8964      no
5944      no
5327      no
15305     no
Name: y, Length: 36168, dtype: object

In [219]:
testcase=xtrain.head().copy()

In [229]:
testcase

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
1533,50,technician,single,tertiary,no,0,yes,no,unknown,8,may,393,2,-1,0,unknown
39881,50,technician,married,secondary,no,3370,no,no,cellular,2,jun,160,2,-1,0,unknown
7432,36,management,single,tertiary,no,0,yes,no,unknown,29,may,211,6,-1,0,unknown
30441,55,blue-collar,married,secondary,no,1765,yes,no,cellular,5,feb,445,1,267,1,failure
39017,28,admin.,single,secondary,no,352,yes,yes,cellular,18,may,431,1,-1,0,unknown

In [223]:
index=testcase.index

In [245]:
for i in (index):
    print('-----------------------------------------------------------------------------------------------------------')
    row=testcase.loc[i]
    print("Customer Case Study # :- ")
    print(row)
    print("The predicted value :- ",catboost.predict(row))
    print("The acutal value:- ",ytrain.loc[i])
    print()
    if catboost.predict(row)==ytrain.loc[i]:
        print('The prediction is correct !!!')
    else:
        print('The prediction is INCORRECT ???')
    print("")
    print()
    print("Probability of NO :- ",catboost.predict_proba(row)[0].round(4))
    print("Probability of YES:- ",catboost.predict_proba(row)[1].round(4))
    print("                                              ===================                         ")

-----------------------------------------------------------------------------------------------------------
Customer Case Study # :-
age                  50
job          technician
marital          single
education      tertiary
default              no
balance               0
housing             yes
loan                 no
contact         unknown
day                   8
month               may
duration            393
campaign              2
pdays                -1
previous              0
poutcome        unknown
Name: 1533, dtype: object
The predicted value :-  no
The acutal value:-  no

The prediction is correct !!!


Probability of NO :-  0.9872
Probability of YES:-  0.0128
                                              ===================
-----------------------------------------------------------------------------------------------------------
Customer Case Study # :-
age                  50
job          technician
marital         married
education     secondary
default              no
balance            3370
housing              no
loan                 no
contact        cellular
day                   2
month               jun
duration            160
campaign              2
pdays                -1
previous              0
poutcome        unknown
Name: 39881, dtype: object
The predicted value :-  yes
The acutal value:-  yes

The prediction is correct !!!


Probability of NO :-  0.1754
Probability of YES:-  0.8246
                                              ===================
-----------------------------------------------------------------------------------------------------------
Customer Case Study # :-
age                  36
job          management
marital          single
education      tertiary
default              no
balance               0
housing             yes
loan                 no
contact         unknown
day                  29
month               may
duration            211
campaign              6
pdays                -1
previous              0
poutcome        unknown
Name: 7432, dtype: object
The predicted value :-  no
The acutal value:-  no

The prediction is correct !!!


Probability of NO :-  0.9965
Probability of YES:-  0.0035
                                              ===================
-----------------------------------------------------------------------------------------------------------
Customer Case Study # :-
age                   55
job          blue-collar
marital          married
education      secondary
default               no
balance             1765
housing              yes
loan                  no
contact         cellular
day                    5
month                feb
duration             445
campaign               1
pdays                267
previous               1
poutcome         failure
Name: 30441, dtype: object
The predicted value :-  no
The acutal value:-  no

The prediction is correct !!!


Probability of NO :-  0.5541
Probability of YES:-  0.4459
                                              ===================
-----------------------------------------------------------------------------------------------------------
Customer Case Study # :-
age                 28
job             admin.
marital         single
education    secondary
default             no
balance            352
housing            yes
loan               yes
contact       cellular
day                 18
month              may
duration           431
campaign             1
pdays               -1
previous             0
poutcome       unknown
Name: 39017, dtype: object
The predicted value :-  yes
The acutal value:-  yes

The prediction is correct !!!


Probability of NO :-  0.2196
Probability of YES:-  0.7804
                                              ===================

In [247]:
joblib.dump(catboost,'model.pkl')

['model.pkl']